# test scheduling and resource allocation using the SMT solver (cvc5)
# (other tests are in subdirectories)

set sources [list \
                 BoolTest AddTest MultTest \
                 DivTest  RemTest \
                 ShiftRTest ShiftRATest ShiftLTest \
                 LessThanSTest LessThanTest \
                 ZextTest SextTest  IteTest \
                 TruncateTest ShiftRATest2 \
		 ArraySelectTest CaseTest \
		 ArraySelectShortIndexTest ArraySelectLongIndexTest \
		 ArraySelectImplCondTest \
		 ParamBoolTest ParamBitsTest \
		 Word64Test SplitTupleMethodTest
                ]


set failures [list]

if {$vtest == 1} {

    foreach s $sources {

        if { [lsearch $failures $s] == -1 } {
            compile_verilog_schedule_pass $s.bsv
            compare_file_filter_ids $s.bsv.bsc-sched-out
        } else {
            compile_verilog_schedule_fail $s.bsv
        }
    }
}
